### ISSUE TITLE
Install script shouldn't use Vim by default

### ISSUE THREAD

**Issue by shymega** [reality/dbot#632]
IMHO, the install script should use the $EDITOR enviroment variable instead of Vim by default. 

Only thing to watch out for is if the $EDITOR variable doesn't exist, in which case install should just use Vim.

**Comment by shymega** [comment]
Just an update on this, the [install](https://github.com/shymega/dbot/blob/newinstall/install) script on my fork's branch is updated with my version of the install script. It now uses the $EDITOR variable to edit config.json, or if that doesn't work it just uses vim. Download URL's have been updated, but I need to test that first before submitting a PR.

**Comment by reality** [comment]
Great! I'll merge that when you can get the pullreq in :)

**Comment by shymega** [comment]
Thanks @reality - PR'ed, let's hope this works! :-)

**Comment by shymega** [comment]
Okay seeing as this is merged and works, closing this issue. See https://github.com/reality/dbot/pull/635 for reference.
