### ISSUE TITLE
tripbot: ~lastdose doesn't specify the timezone linked to the timestamp

### ISSUE THREAD

**Issue by ViralTaco** [reality/dbot#685]
It's in the title. 
I just took my medication 1 hourly earlier than I should have because I trusted the timestamp more than then the time interval approximation. 
I'll start working on a fix right away and submit a pull request (which will not get noticed in years if ever). I'm about to fork this, seriously, @reality, do you still intend to update dbot or not?

**Comment by ViralTaco** [comment]
Closed. Wrong fork, I guess. Not sure. Jesus Christ this project didn't age well.

**Comment by reality** [comment]
https://github.com/TripSit/idose - although the code does seem to use the timezone - i wonder what the issue is

**Comment by ViralTaco** [comment]
Hey reality, long time no see. Sorry I was pissed off yesterday. Thanks for the link, I couldn't find it anywhere. I'll look into making a pull request. (I'll add an issue there)
